version: "3"
services:
  cinemacatalogservice:
    container_name: cinemacatalogservice
    restart: always
    build: .
    ports:
      - "8080:3010"
    links:
      - mongo
    networks: 
      - ccs-mongo-compose-network
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment: 
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    volumes:
      - ./data:/data/db
    ports:
      - "27019:27017"
    networks: 
      - ccs-mongo-compose-network    
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    networks: 
      - ccs-mongo-compose-network
    ports:
      - 3082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    volumes: 
      - ./data:/data/db
networks:
  ccs-mongo-compose-network:
    driver: bridge  